---
- hosts: '{{ target }}'
  remote_user: root

  vars_prompt:
    - name: enroll
      prompt: "Enroll user password"
  vars: # See README for link to install freeipa-client module
    freeipaclient_server: "freeipa.thedavid.center"
    freeipaclient_domain: thedavid.center
    freeipaclient_enroll_user: admin
    freeipaclient_enroll_pass: "{{ vars.enroll }}"
  roles:
    - alvaroaleman.freeipa-client

  tasks:
  - block:
    - name: Update all RHEL packages
      yum:
        name: '*'
        state: latest
      tags: update
  
    - name: Install epel-release
      yum: name=epel-release state=latest update_cache=yes
    - name: Install standard packages
      yum: name={{item}} state=latest update_cache=yes
      with_items:
        - vim
        - screen
        - wget
        - firewalld
        - git
        - ipa-client
      tags: packages
    when: ansible_os_family == "RedHat"

  - block:
    - name: Update all Debian packages
      apt:
        name: '*' 
        state: latest
        force_apt_get: yes 
      tags: update
  
    - name: Install standard packages
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - screen
        - wget
        - git
      tags: packages
    when: ansible_os_family == "Debian"

  - block:
    - name: Start and enable firewalld
      service: name=firewalld state=started enabled=yes
  
    - name: Enable FreeIPA-client firewall rules
      firewalld: port=464/tcp permanent=true state=enabled
    - name: FreeIPA-client firewall rules continued
      firewalld: port=464/udp permanent=true state=enabled
    - name: Prometheus node_exporter firewall rule
      firewalld: port=9100/tcp permanent=true state=enabled
  
    - name: Reload firewall
      command: firewall-cmd --reload
    when: ansible_os_family == "RedHat"

  - block:
    - name: Start and enable ufw.service
      systemd:
        name: ufw 
        state: started
        enabled: yes 
  
    - name: enable ufw 
      ufw:
        state: enabled
  
    - name: FreeIPA-client tcp firewall rules
      ufw:
        rule: allow
        port: 464 
        proto: tcp 
    - name: FreeIPA-client udp firewall rules
      ufw:
        rule: allow
        port: 464 
        proto: udp 
    - name: Allow SSH access
      ufw:
        rule: allow
        name: OpenSSH
    - name: Allow Prometheus node_exporter
      ufw:
        rule: allow
        port: 9100
        proto: tcp
    when: ansible_os_family == "Debian"

  - block:
    - name: Start and Enable oddjobd
      systemd:
        name: oddjobd
        state: started
        enabled: yes
    
    - name: Make sure NetworkManager is stopped and disabled
      systemd:
        name: NetworkManager
        state: stopped
        enabled: no
    when: ansible_os_family == "RedHat"

...
