---
- hosts: '{{ target }}'
  remote_user: root

  tasks:
  - name: Update all packages
    apt:
      name: '*'
      state: latest
      force_apt_get: yes
  - name: Install standard packages
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - vim
      - screen
      - wget
      - git
      - libgetopt-mixed-perl
      - libmcrypt4
  - name: Install Opsview Agent
    apt:
      deb: https://s3.amazonaws.com/opsview-agents/ubuntu16/opsview-agent_5.4.1.172541017-1xenial1_amd64.deb

  - name: Start and enable ufw.service
    systemd:
      name: ufw
      state: started
      enabled: yes

  - name: enable ufw
    ufw:
      state: enabled

  - name: FreeIPA-client tcp firewall rules
    ufw:
      rule: allow
      port: 464
      proto: tcp
  - name: FreeIPA-client udp firewall rules
    ufw:
      rule: allow
      port: 464
      proto: udp
  - name: Enable opsview-agent firewall rules
    ufw:
      rule: allow
      port: 5666
      proto: tcp

  vars_prompt:
    - name: enroll
      prompt: "Enroll user password"
  vars: # See README for link to install freeipa-client module
    freeipaclient_server: "freeipa.thedavid.center"
    freeipaclient_domain: thedavid.center
    freeipaclient_enroll_user: admin
    freeipaclient_enroll_pass: "{{ vars.enroll }}"
  roles:
    - alvaroaleman.freeipa-client

...
